// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiYffBunyb8Y673IsM-vuliedH2MMbkkk',
    appId: '1:672634764795:web:ca25260ef24a16a1bddf5e',
    messagingSenderId: '672634764795',
    projectId: 'jsonleagueunlimited',
    authDomain: 'jsonleagueunlimited.firebaseapp.com',
    storageBucket: 'jsonleagueunlimited.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfWF7Omo16TxpAi7YTJytAkhLmxzAdYI',
    appId: '1:672634764795:android:1a13d3ded7b14ecebddf5e',
    messagingSenderId: '672634764795',
    projectId: 'jsonleagueunlimited',
    storageBucket: 'jsonleagueunlimited.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKZc-ZNq4lBK8YiTThMIIsjZd4PY_3RU',
    appId: '1:672634764795:ios:d95cf493d9917ae1bddf5e',
    messagingSenderId: '672634764795',
    projectId: 'jsonleagueunlimited',
    storageBucket: 'jsonleagueunlimited.appspot.com',
    iosClientId: '672634764795-ekresf246rtvpcac00579o1990nrg3b3.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsonLeague',
  );
}
